# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'Team Up' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Team Up
	pod 'SwiftyJSON'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
end
